### ISSUE TITLE
Not working on html5

### ISSUE THREAD

**Issue by Olivier-Malige** [dploeger/godot-scrollingbackground#1]
Hi, I have a problem with the background that does not work when I export in html 5

**Comment by dploeger** [comment]
I can reproduce that, but I'm currently a bit stumped on why this happens. I'm investigating.

**Comment by Olivier-Malige** [comment]
I could only test it on the version of godot 2.1.4, but I doubt that the addon works with the version 3, it seems to me that it has differences with the management of the html. thank you to do the birth if possible, because your addon is handy when you want to scroll a background without moving the camera.

**Comment by dploeger** [comment]
Yes, I know. I'm already trying to port it to Godot 3. Maybe it works in HTML5 there. I'll keep you posted.

**Comment by dploeger** [comment]
I just pushed the latest release 3.0.2 to the Godot asset library (It will probably take a few hours until it's available there). I could perfectly export a working project with Godot 3. Could you please try that?
