### ISSUE TITLE
Asset library page can be improved

### ISSUE THREAD

**Issue by bojidar-bg** [dploeger/godot-scrollingbackground#2]
I.e. https://godotengine.org/asset-library/asset/86

1. The icon is missing, as it points to `scrolling_sprite` instead of `scrolling_background`
2. The preview is a gif, which won't work in the editor but only online. Consider adding a PNG preview as well.

Looks like this in the editor:
![image](https://user-images.githubusercontent.com/5276727/35615279-5b35235a-067a-11e8-9dae-f69e0ced4a93.png)

**Comment by dploeger** [comment]
Done that and send a new edit. Thanks!
