### ISSUE TITLE
Background covers all other sprites

### ISSUE THREAD

**Issue by bgordley** [dploeger/godot-scrollingbackground#3]
I am finding that, when running a game, the scrolling background covers all content on the screen. I have searched through the GDScript and am not sure what could be causing this.

Below is my hierarchy.
- Node2D
  - ScrollingBackground
  - PlayerPrefab

Let me know if more data is needed.

**Comment by dploeger** [comment]
Yes, that's the expected behavior. The way the plug-in works is that it spans the image one texture width wider over the whole screen, moves it across the screen and skips it back to the original position. This creates the illusion of an endless scrolling.

If you only need a small portion of it, I'd have to come up with another idea for this.

**Comment by bgordley** [comment]
Sorry, I wasn't very clear in my initial comment.

What I am seeing is that my player is appearing underneath the scrolling background. It seems like the scrolling background is moving to the top of the node order, covering all other sprites completely.

**Comment by bgordley** [comment]
I should also note that I am using this plugin via the newest version of Godot 3.

**Comment by dploeger** [comment]
Ah, okay. Are you using version 3.0.1 of this plug-in?

**Comment by bgordley** [comment]
My apologies for the delayed response. Yes, I am using version 3.0.1

**Comment by dploeger** [comment]
Hm. I can not reproduce it. Do you perhaps can provide a sample project?

**Comment by dploeger** [comment]
Additionally, I just pushed version 3.0.2 to the Godot asset library (It will probably take a few hours until it's available there). The fix was about another bug, but perhaps it helps you as well.

**Comment by bgordley** [comment]
I will give it another shot and let you know if the issue is resolved. If not I will send a sample project your way.
