### ISSUE TITLE
Change values to float instead of intigers

### ISSUE THREAD

**Issue by fm-frga** [dploeger/godot-scrollingbackground#4]
I found that -1 speed scrolls my background too fast. I tried to change it but your script has INT and I'm not sure how to change it and since is your code I probably don't have permission to change it.

**Comment by dploeger** [comment]
Hey! Of course you have. This is an open source plugin. 😁 
Seriously, just fork this repository and change the code the way you want and send me a [pull request](https://help.github.com/articles/about-pull-requests/) with the changed code. I'll be happy to check it out.
I'm currently a bit swamped with other things.
